/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;
import codes.DBconnect;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.*;
import java.util.Calendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
//import java.sql.Date;
import java.util.Date;
/**
 *
 * @author ASUS
 */
public class EmloyeeSignInLast extends javax.swing.JFrame {
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form EmloyeeSignInLast
     */
    public EmloyeeSignInLast() {
        super("Sign In");
        initComponents();
        //conn=javaConnect.connecrDb();
        conn=DBconnect.connect();
        comboSQ.setSelectedItem(null);
        
    }
    String imgPath=null;
    public ImageIcon ResizeImage(String ImagePath, byte[] pic){
        ImageIcon MyImage=null;
        if(ImagePath !=null){
            MyImage=new ImageIcon(ImagePath);
        }else{
            MyImage=new ImageIcon(pic);
        }
        Image img =MyImage.getImage();
        Image newImg=img.getScaledInstance(lblPhoto.getWidth(),lblPhoto.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(newImg);
        return image;
    }
    
    
    public void cle(){
        //jTextArea3.setText(null);
        comboSQ.setSelectedItem(null);
        txtAnswer.setText(null);
        AC_Password.setText(null);
        lblPhoto.setIcon(null);
        txtEmpId.setText(null);
        txtS_A_Password.setText(null); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        signinpanel = new javax.swing.JPanel();
        lblp = new javax.swing.JLabel();
        empibl = new javax.swing.JLabel();
        txtEmpId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblPhoto = new javax.swing.JLabel();
        sqlbl = new javax.swing.JLabel();
        comboSQ = new javax.swing.JComboBox<>();
        passwordlbl = new javax.swing.JLabel();
        txtAnswer = new javax.swing.JTextField();
        anslbl = new javax.swing.JLabel();
        AC_Password = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        Displaypnal = new javax.swing.JPanel();
        emplbl = new javax.swing.JLabel();
        txtS_A_User_Name = new javax.swing.JTextField();
        pslbl = new javax.swing.JLabel();
        txtS_A_Password = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));

        signinpanel.setBackground(new java.awt.Color(0, 51, 255,80));
        signinpanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "Sign In", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 204, 204))); // NOI18N
        signinpanel.setForeground(new java.awt.Color(0, 204, 204));

        lblp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblp.setForeground(new java.awt.Color(255, 255, 255));
        lblp.setText("Photo");

        empibl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        empibl.setForeground(new java.awt.Color(255, 255, 255));
        empibl.setText("Employee ID");

        txtEmpId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpIdActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        sqlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sqlbl.setForeground(new java.awt.Color(255, 255, 255));
        sqlbl.setText(" Security Question");

        comboSQ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your mother toungue?", "What is Your nick name?", "Who is your first child hood hero?", "What is your school name?" }));

        passwordlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passwordlbl.setForeground(new java.awt.Color(255, 255, 255));
        passwordlbl.setText("Password");

        anslbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        anslbl.setForeground(new java.awt.Color(255, 255, 255));
        anslbl.setText("Answer");

        AC_Password.setText("jPasswordField1");

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sign In");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signinpanelLayout = new javax.swing.GroupLayout(signinpanel);
        signinpanel.setLayout(signinpanelLayout);
        signinpanelLayout.setHorizontalGroup(
            signinpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signinpanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(signinpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signinpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(empibl)
                        .addComponent(lblp, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(anslbl)
                    .addComponent(passwordlbl)
                    .addComponent(sqlbl))
                .addGap(33, 33, 33)
                .addGroup(signinpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AC_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(signinpanelLayout.createSequentialGroup()
                        .addComponent(txtEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signinpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(117, 117, 117))
        );
        signinpanelLayout.setVerticalGroup(
            signinpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signinpanelLayout.createSequentialGroup()
                .addGroup(signinpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signinpanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(signinpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empibl)
                            .addComponent(txtEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(signinpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGroup(signinpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signinpanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblp))
                    .addGroup(signinpanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(signinpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sqlbl)
                    .addComponent(comboSQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(signinpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anslbl))
                .addGap(26, 26, 26)
                .addGroup(signinpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordlbl)
                    .addComponent(AC_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(signinpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 450, 460));

        Displaypnal.setBackground(new java.awt.Color(0, 51, 255,80));
        Displaypnal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "System Access", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 204, 204))); // NOI18N

        emplbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emplbl.setForeground(new java.awt.Color(255, 255, 255));
        emplbl.setText("User ID");

        pslbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pslbl.setForeground(new java.awt.Color(255, 255, 255));
        pslbl.setText("Password");

        javax.swing.GroupLayout DisplaypnalLayout = new javax.swing.GroupLayout(Displaypnal);
        Displaypnal.setLayout(DisplaypnalLayout);
        DisplaypnalLayout.setHorizontalGroup(
            DisplaypnalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplaypnalLayout.createSequentialGroup()
                .addGroup(DisplaypnalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DisplaypnalLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(DisplaypnalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtS_A_User_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtS_A_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DisplaypnalLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(pslbl)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DisplaypnalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(emplbl)
                .addGap(63, 63, 63))
        );
        DisplaypnalLayout.setVerticalGroup(
            DisplaypnalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplaypnalLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(emplbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtS_A_User_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(pslbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtS_A_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(Displaypnal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 180, 220));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EmpSignIN bluee.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 782, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmpIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpIdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        /* int EId;
        String  empId=txtEmpId.getText();
        EId = Integer.parseInt(empId);*/
         int EId;
            String  empId=txtEmpId.getText();
            EId = Integer.parseInt(empId);
        //display image
         try {
        String sql = "SELECT * FROM employee WHERE EmpId = ?";
        pst = conn.prepareStatement(sql);
        pst.setInt(1,EId);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            

            
           lblPhoto.setIcon(ResizeImage(null,rs.getBytes("Profile_Photo")));
            
            
        } else {
            JOptionPane.showMessageDialog(null, "Employee  with ID " + EId + " not found.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        //end disply image
        
        
        
        try{
            // SELECT Job_Type FROM `employee` WHERE EmpId =?;
          /*  int EId;
            String  empId=txtEmpId.getText();
            EId = Integer.parseInt(empId);
          */
            String sqll="UPDATE employee SET Sequrity_Question = ?, Answer = ?, Account_Password = ? WHERE EmpId =?";

            pst=conn.prepareStatement(sqll);

            pst.setString(1,(String) comboSQ.getSelectedItem());
            pst.setString(2,txtAnswer.getText());
            pst.setString(3,AC_Password.getText());
            pst.setInt(4,EId);

            int rowsAffected = pst.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "You have signed in.");
            } else {
                JOptionPane.showMessageDialog(null, "No records updated");
            }
            //pst.execute();

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

        try{
            /*
            int EId;
            String  empId=txtEmpId.getText();
            EId = Integer.parseInt(empId);*/

            String sql3="select job_Type from employee where EmpId = ?";
            pst=conn.prepareStatement(sql3);
            pst.setInt(1,EId);
            rs=pst.executeQuery();
            if(rs.next()){
                String Job=rs.getString("Job_Type");

                //--------
                String sql2="select Job_Type,Account_Password from employee where Job_Type='"+Job+"'  and EmpId = ?";
                try{
                    pst=conn.prepareStatement(sql2);
                    pst.setInt(1,EId);
                    rs=pst.executeQuery();
                    if(rs.next()){
                        //txtS_A_User_Name.setText(rs.getString(1));
                        txtS_A_User_Name.setText(String.valueOf(EId));
                       // txtS_A_User_Name.setInt(EId);
                        txtS_A_Password.setText(rs.getString(2));
                    }

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int EId;
            String  empId=txtEmpId.getText();
            EId = Integer.parseInt(empId);
        //display image
         try {
        String sql = "SELECT * FROM employee WHERE EmpId = ?";
        pst = conn.prepareStatement(sql);
        pst.setInt(1,EId);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            

            
           lblPhoto.setIcon(ResizeImage(null,rs.getBytes("Profile_Photo")));
            
            
        } else {
            JOptionPane.showMessageDialog(null, "Employee  with ID " + EId + " not found.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Login ob=new Login();
        ob.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmloyeeSignInLast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmloyeeSignInLast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmloyeeSignInLast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmloyeeSignInLast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmloyeeSignInLast().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField AC_Password;
    private javax.swing.JPanel Displaypnal;
    private javax.swing.JLabel anslbl;
    private javax.swing.JComboBox<String> comboSQ;
    private javax.swing.JLabel empibl;
    private javax.swing.JLabel emplbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblp;
    private javax.swing.JLabel passwordlbl;
    private javax.swing.JLabel pslbl;
    private javax.swing.JPanel signinpanel;
    private javax.swing.JLabel sqlbl;
    private javax.swing.JTextField txtAnswer;
    private javax.swing.JTextField txtEmpId;
    private javax.swing.JTextField txtS_A_Password;
    private javax.swing.JTextField txtS_A_User_Name;
    // End of variables declaration//GEN-END:variables
}
